spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ebus
    username: postgres
    password: ikram
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: update
    show-sql: true
