// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIB3-Ign5jm-RkOaxxTvtj2jxlK0Q3w68',
    appId: '1:9061511448:web:53929ef6088ec5f5b5ae6d',
    messagingSenderId: '9061511448',
    projectId: 'ebus-6311b',
    authDomain: 'ebus-6311b.firebaseapp.com',
    storageBucket: 'ebus-6311b.firebasestorage.app',
    measurementId: 'G-WCWYL97NJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClP8t_gsihoZonB0ZAvI9HBJL5fwXZ8EI',
    appId: '1:9061511448:android:482386c7bb44891ab5ae6d',
    messagingSenderId: '9061511448',
    projectId: 'ebus-6311b',
    storageBucket: 'ebus-6311b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk8rpQUmTjAaVtkiXi_4ewH74gCvbFkHQ',
    appId: '1:9061511448:ios:5b8e56d7a28f32d7b5ae6d',
    messagingSenderId: '9061511448',
    projectId: 'ebus-6311b',
    storageBucket: 'ebus-6311b.firebasestorage.app',
    iosBundleId: 'com.example.smartBus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIB3-Ign5jm-RkOaxxTvtj2jxlK0Q3w68',
    appId: '1:9061511448:web:a639fe5895cf24b7b5ae6d',
    messagingSenderId: '9061511448',
    projectId: 'ebus-6311b',
    authDomain: 'ebus-6311b.firebaseapp.com',
    storageBucket: 'ebus-6311b.firebasestorage.app',
    measurementId: 'G-Q6FZFYLYKT',
  );
}
